/**
 * The cast from an authored object to a `jsonb` column.
 *
 * Postgres `jsonb` arrives from the type generator as `Json`, a recursive union
 * that nothing we author structurally satisfies — a `Persona`'s dials or a
 * scorecard's metrics are perfectly good JSON and are still not assignable to
 * it. Every insert into a `jsonb` column therefore needs one cast, and this is
 * that cast, named, so the reason survives and so `any` never appears at a call
 * site.
 *
 * **It lives here and not in `lib/db/types.ts` on purpose.** That file is
 * generated by `npm run db:types`, which overwrites it whole — a helper
 * appended to the bottom of it survives exactly until the next schema change,
 * and then vanishes with a compile error that looks like the generator's fault.
 */

import type { Json } from './types'

export function asJson(value: unknown): Json {
  return value as Json
}
