/**
 * Collected transcripts for the grade calibration suite (§07, §17).
 *
 * **Generated by `npm run grade:collect`. Do not hand-edit.** The hand-scored
 * expectations live in `fixtures.ts`, keyed by id, precisely so that
 * re-collecting can never clobber scoring work somebody did by reading.
 *
 * Every rep here ran under the current three-minute format. A transcript from
 * a two-minute rep is the wrong shape to score a three-minute one, which is
 * why the format changed before anything else in M2.
 */

export interface CollectedTranscript {
  id: string
  /** Where it came from, so a disputed score can be read again in full. */
  source: string
  personaName: string
  sessionSeconds: number
  transcript: { speaker: 'user' | 'agent'; text: string; t_start: number; t_end: number }[]
}

export const CALIBRATION_TRANSCRIPTS: CollectedTranscript[] = [
  {
    "id": "maya-2026-08-23-390137",
    "source": "session 3901374e-c86f-46a2-bbac-63010688bfa6",
    "personaName": "Maya",
    "sessionSeconds": 184,
    "transcript": [
      {
        "text": "Hey Maya, I recently read Kafka on the Shore, like you recommended, and I really loved it.",
        "t_end": 6.348,
        "speaker": "user",
        "t_start": 1.225
      },
      {
        "text": "Good. What stuck with you?",
        "t_end": 9.982,
        "speaker": "agent",
        "t_start": 6.857
      },
      {
        "text": "Yeah, I mean, it's just a really nice story with interesting characters.",
        "t_end": 14.508,
        "speaker": "user",
        "t_start": 9.982
      },
      {
        "text": "You got a favorite part or not?",
        "t_end": 17.221,
        "speaker": "agent",
        "t_start": 15.063
      },
      {
        "text": "I mean, generally, overall, I like the entire story. What about you? What's your favorite, most favorite scene?",
        "t_end": 25.177,
        "speaker": "user",
        "t_start": 18.503
      },
      {
        "text": "The diner scene, hands down.",
        "t_end": 27.963,
        "speaker": "agent",
        "t_start": 25.82
      },
      {
        "text": "So, you're still sketching them?",
        "t_end": 31.84,
        "speaker": "user",
        "t_start": 29.66
      },
      {
        "text": "Yeah, still sketching, badly.",
        "t_end": 32.905,
        "speaker": "agent",
        "t_start": 32.324
      },
      {
        "text": "Not today. Just the notebook.",
        "t_end": 36.997,
        "speaker": "agent",
        "t_start": 34.031
      },
      {
        "text": "Yeah, some notes and a",
        "t_end": 40.431,
        "speaker": "agent",
        "t_start": 40.235
      },
      {
        "text": "So, what are you having to drink today?",
        "t_end": 46.671,
        "speaker": "user",
        "t_start": 44.046
      },
      {
        "text": "Oat flat white, almost finished.",
        "t_end": 50.283,
        "speaker": "agent",
        "t_start": 47.232
      },
      {
        "text": "You are really into flat white, aren't you?",
        "t_end": 54.35,
        "speaker": "user",
        "t_start": 51.741
      },
      {
        "text": "It does the job for me, yeah.",
        "t_end": 57.321,
        "speaker": "agent",
        "t_start": 54.828
      },
      {
        "text": "So are you a coffee girl or a tea girl?",
        "t_end": 62.564,
        "speaker": "user",
        "t_start": 59.018
      },
      {
        "text": "Coffee mostly, but I don't hate tea.",
        "t_end": 67.406,
        "speaker": "agent",
        "t_start": 63.024
      },
      {
        "text": "Tea never really stood it with me. I mean, it's just basically flavoured water.",
        "t_end": 72.269,
        "speaker": "user",
        "t_start": 67.646
      },
      {
        "text": "Flavored water can be good, though.",
        "t_end": 75.581,
        "speaker": "agent",
        "t_start": 72.738
      },
      {
        "text": "I mean, yeah, I mean, basically every drink is a flavored water type, right?",
        "t_end": 81.038,
        "speaker": "user",
        "t_start": 76.339
      },
      {
        "text": "That’s the baseline, sure, just dressed up water.",
        "t_end": 85.382,
        "speaker": "agent",
        "t_start": 81.562
      },
      {
        "text": "So what's new with you?",
        "t_end": 88.705,
        "speaker": "user",
        "t_start": 86.877
      },
      {
        "text": "Got through a dull week at work, that’s new.",
        "t_end": 92.264,
        "speaker": "agent",
        "t_start": 89.175
      },
      {
        "text": "Really? Where do you work, by the way?",
        "t_end": 95.723,
        "speaker": "user",
        "t_start": 93.406
      },
      {
        "text": "Mid-sized company, doing accounts.",
        "t_end": 99.241,
        "speaker": "agent",
        "t_start": 96.467
      },
      {
        "text": "Counted, huh? So you must be pretty good with numbers.",
        "t_end": 103.294,
        "speaker": "user",
        "t_start": 100.142
      },
      {
        "text": "Good enough to keep the lights on.",
        "t_end": 105.482,
        "speaker": "agent",
        "t_start": 103.772
      },
      {
        "text": "Any advice on someone asking to be an accountant?",
        "t_end": 112.208,
        "speaker": "user",
        "t_start": 108.124
      },
      {
        "text": "Brace for boredom, and learn shortcuts.",
        "t_end": 115.742,
        "speaker": "agent",
        "t_start": 112.704
      },
      {
        "text": "So if you do accounting, and what do you do for fun besides catching and drinking coffee?",
        "t_end": 123.383,
        "speaker": "user",
        "t_start": 116.445
      },
      {
        "text": "Bad movies, long walks, sometimes both.",
        "t_end": 127.482,
        "speaker": "agent",
        "t_start": 123.849
      },
      {
        "text": "You are really my type. What's your favorite worst movie?",
        "t_end": 133.991,
        "speaker": "user",
        "t_start": 129.842
      },
      {
        "text": "\"Troll 2\"—it's awful in the best way.",
        "t_end": 137.66,
        "speaker": "agent",
        "t_start": 134.514
      },
      {
        "text": "Okay, mine's a superhero movie.",
        "t_end": 143.445,
        "speaker": "user",
        "t_start": 138.94
      },
      {
        "text": "What, the one that’s literally called \"Superhero Movie\"?",
        "t_end": 147.281,
        "speaker": "agent",
        "t_start": 143.978
      },
      {
        "text": "Exactly.",
        "t_end": 149.195,
        "speaker": "user",
        "t_start": 147.851
      },
      {
        "text": "That’s a bold pick. You watching it ironically or not?",
        "t_end": 153.921,
        "speaker": "agent",
        "t_start": 149.72
      },
      {
        "text": "Yeah, definitely, ironically, it's quite funny. And I also like the Hangover series as well.",
        "t_end": 160.042,
        "speaker": "user",
        "t_start": 154.143
      },
      {
        "text": "Yeah, the first one still holds up.",
        "t_end": 164,
        "speaker": "agent",
        "t_start": 160.557
      },
      {
        "text": "Okay then, what's your favorite best movie?",
        "t_end": 167.021,
        "speaker": "user",
        "t_start": 164.198
      },
      {
        "text": "Not giving that away this time. You’ll have to guess.",
        "t_end": 170.961,
        "speaker": "agent",
        "t_start": 167.88
      },
      {
        "text": "Maybe I can get it by your number.",
        "t_end": 174.742,
        "speaker": "user",
        "t_start": 171.857
      },
      {
        "text": "Timing’s off, nice try though.",
        "t_end": 177.506,
        "speaker": "agent",
        "t_start": 175.274
      }
    ]
  },
  {
    "id": "jules-2026-08-23-5c3d6d",
    "source": "session 5c3d6d3d-479c-46a3-8b8c-b5fc88e4f3ce",
    "personaName": "Jules",
    "sessionSeconds": 154,
    "transcript": [
      {
        "text": "It's crowded out here, isn't it?",
        "t_end": 4.501,
        "speaker": "user",
        "t_start": 2.434
      },
      {
        "text": "Yeah, packed in.",
        "t_end": 6.873,
        "speaker": "agent",
        "t_start": 5.159
      },
      {
        "text": "So what are you doing here?",
        "t_end": 11.543,
        "speaker": "user",
        "t_start": 10.016
      },
      {
        "text": "Catching up, that’s all.",
        "t_end": 14.137,
        "speaker": "agent",
        "t_start": 12.109
      },
      {
        "text": "I see, you are talking with friends, right? Am I disturbing?",
        "t_end": 18.859,
        "speaker": "user",
        "t_start": 15.456
      },
      {
        "text": "Not yet.",
        "t_end": 21.794,
        "speaker": "agent",
        "t_start": 19.468
      },
      {
        "text": "Sure, what's your name?",
        "t_end": 24.099,
        "speaker": "user",
        "t_start": 22.653
      },
      {
        "text": "Jules. Yours?",
        "t_end": 25.573,
        "speaker": "agent",
        "t_start": 24.715
      },
      {
        "text": "Hey Jules, you remind me of a person I saw on Euphoria TV series.",
        "t_end": 34.059,
        "speaker": "user",
        "t_start": 27.221
      },
      {
        "text": "Huh, do I have that vibe?",
        "t_end": 36.952,
        "speaker": "agent",
        "t_start": 35.053
      },
      {
        "text": "Yeah, you kind of do.",
        "t_end": 39.914,
        "speaker": "user",
        "t_start": 38.338
      },
      {
        "text": "Guess I’ll take that, thanks.",
        "t_end": 42.413,
        "speaker": "agent",
        "t_start": 40.505
      },
      {
        "text": "And you dress sharp as well.",
        "t_end": 45.643,
        "speaker": "user",
        "t_start": 43.755
      },
      {
        "text": "Just threw this on, honestly.",
        "t_end": 48.193,
        "speaker": "agent",
        "t_start": 46.212
      },
      {
        "text": "Really, it looks like you really thought about that outfit. Matches the vibe.",
        "t_end": 55.092,
        "speaker": "user",
        "t_start": 49.801
      },
      {
        "text": "Well, maybe a little thought slipped in.",
        "t_end": 58.435,
        "speaker": "agent",
        "t_start": 55.815
      },
      {
        "text": "So, who are your friends?",
        "t_end": 62.928,
        "speaker": "user",
        "t_start": 59.886
      },
      {
        "text": "Just an old school friend here.",
        "t_end": 66.568,
        "speaker": "agent",
        "t_start": 63.543
      },
      {
        "text": "Oh, really? Where did you go to school?",
        "t_end": 68.641,
        "speaker": "user",
        "t_start": 66.567
      },
      {
        "text": "Same town, just outside the city.",
        "t_end": 72.834,
        "speaker": "agent",
        "t_start": 72.595
      },
      {
        "text": "I'm not from here, so probably I don't know.",
        "t_end": 77.622,
        "speaker": "user",
        "t_start": 73.939
      },
      {
        "text": "Yeah, local spot, no big deal.",
        "t_end": 81.372,
        "speaker": "agent",
        "t_start": 78.382
      },
      {
        "text": "Any advice on the locals' part?",
        "t_end": 86.475,
        "speaker": "user",
        "t_start": 83.656
      },
      {
        "text": "Depends what you’re looking for, really.",
        "t_end": 89.612,
        "speaker": "agent",
        "t_start": 87.093
      },
      {
        "text": "I'm looking to have a good time.",
        "t_end": 92.517,
        "speaker": "user",
        "t_start": 90.661
      },
      {
        "text": "Plenty of bars, live music spots around.",
        "t_end": 96.572,
        "speaker": "agent",
        "t_start": 93.132
      },
      {
        "text": "You enjoy live music?",
        "t_end": 99.455,
        "speaker": "user",
        "t_start": 97.756
      },
      {
        "text": "Yeah, when it’s decent and not too loud.",
        "t_end": 102.552,
        "speaker": "agent",
        "t_start": 100.107
      },
      {
        "text": "What's your favorite artist?",
        "t_end": 105.421,
        "speaker": "user",
        "t_start": 103.593
      },
      {
        "text": "Changes all the time, honestly.",
        "t_end": 108.051,
        "speaker": "agent",
        "t_start": 106.026
      },
      {
        "text": "Makes sense.",
        "t_end": 111.1,
        "speaker": "user",
        "t_start": 109.816
      },
      {
        "text": "Keeps it interesting that way.",
        "t_end": 113.372,
        "speaker": "agent",
        "t_start": 111.695
      },
      {
        "text": "So how about currently? Who's your current favorite artist?",
        "t_end": 118.729,
        "speaker": "user",
        "t_start": 115.114
      },
      {
        "text": "Right now, maybe Wet Leg.",
        "t_end": 121.573,
        "speaker": "agent",
        "t_start": 119.361
      },
      {
        "text": "What they? I haven't even heard of them.",
        "t_end": 125.262,
        "speaker": "user",
        "t_start": 122.74
      },
      {
        "text": "Fun indie duo, pretty catchy stuff.",
        "t_end": 128.812,
        "speaker": "agent",
        "t_start": 125.869
      },
      {
        "text": "That's awesome. Maybe I should give them a try.",
        "t_end": 132.783,
        "speaker": "user",
        "t_start": 130.013
      },
      {
        "text": "Worth a listen, if you’re curious.",
        "t_end": 135.219,
        "speaker": "agent",
        "t_start": 133.409
      },
      {
        "text": "Hope you enjoy the dive in.",
        "t_end": 137.078,
        "speaker": "agent",
        "t_start": 136.449
      },
      {
        "text": "Yeah, I am a curious person.",
        "t_end": 139.221,
        "speaker": "user",
        "t_start": 137.078
      },
      {
        "text": "Nothing wrong with that here.",
        "t_end": 142.847,
        "speaker": "agent",
        "t_start": 139.809
      },
      {
        "text": "Maybe I can get your number?",
        "t_end": 146.285,
        "speaker": "user",
        "t_start": 144.419
      },
      {
        "text": "Bit quick for that, don’t you think?",
        "t_end": 149.332,
        "speaker": "agent",
        "t_start": 147.103
      },
      {
        "text": "Mi you sak.",
        "t_end": 152.321,
        "speaker": "user",
        "t_start": 150.71
      },
      {
        "text": "Alright, that’s done.",
        "t_end": 154.379,
        "speaker": "agent",
        "t_start": 152.911
      }
    ]
  },
  {
    "id": "maya-2026-08-23-48b7e6",
    "source": "session 48b7e6a3-9ec9-4ec8-ae8e-7583606ce511",
    "personaName": "Maya",
    "sessionSeconds": 184,
    "transcript": [
      {
        "text": "Hello.",
        "t_end": 2.152,
        "speaker": "user",
        "t_start": 1.272
      },
      {
        "text": "Morning. It’s quiet in here.",
        "t_end": 3.722,
        "speaker": "agent",
        "t_start": 2.684
      },
      {
        "text": "Morning.",
        "t_end": 4.976,
        "speaker": "agent",
        "t_start": 4.847
      },
      {
        "text": "Good morning, what's your name?",
        "t_end": 6.706,
        "speaker": "user",
        "t_start": 4.976
      },
      {
        "text": "Maya. That's it.",
        "t_end": 8.977,
        "speaker": "agent",
        "t_start": 7.148
      },
      {
        "text": "Hey Mia, your coffee looks delicious. What is that?",
        "t_end": 13.106,
        "speaker": "user",
        "t_start": 9.862
      },
      {
        "text": "Oat flat white, two-thirds done.",
        "t_end": 16.517,
        "speaker": "agent",
        "t_start": 13.626
      },
      {
        "text": "Beautiful day today, isn't it?",
        "t_end": 19.625,
        "speaker": "user",
        "t_start": 17.69
      },
      {
        "text": "Bright enough. Wind’s picking up though.",
        "t_end": 23.064,
        "speaker": "agent",
        "t_start": 20.062
      },
      {
        "text": "Are you a girl who likes windy days or normal days?",
        "t_end": 29.139,
        "speaker": "user",
        "t_start": 24.663
      },
      {
        "text": "Normal days, mostly.",
        "t_end": 32.036,
        "speaker": "agent",
        "t_start": 29.601
      },
      {
        "text": "How about your favorite season?",
        "t_end": 35.379,
        "speaker": "user",
        "t_start": 33.413
      },
      {
        "text": "Autumn. Chilly, not freezing.",
        "t_end": 38.857,
        "speaker": "agent",
        "t_start": 35.793
      },
      {
        "text": "Right.",
        "t_end": 40.25,
        "speaker": "agent",
        "t_start": 39.993
      },
      {
        "text": "So what are you writing there?",
        "t_end": 41.94,
        "speaker": "user",
        "t_start": 40.25
      },
      {
        "text": "Just some messy sketches, nothing fancy.",
        "t_end": 45.958,
        "speaker": "agent",
        "t_start": 42.367
      },
      {
        "text": "Skeges, huh? So you are an artist.",
        "t_end": 48.552,
        "speaker": "user",
        "t_start": 45.958
      },
      {
        "text": "Not really, I just draw for fun.",
        "t_end": 52.774,
        "speaker": "agent",
        "t_start": 48.986
      },
      {
        "text": "That's really cool.",
        "t_end": 54.24,
        "speaker": "user",
        "t_start": 52.773
      },
      {
        "text": "It's more clumsy than cool, trust me.",
        "t_end": 57.376,
        "speaker": "agent",
        "t_start": 54.688
      },
      {
        "text": "Okay, I trust you. How old are you, by the way?",
        "t_end": 61.994,
        "speaker": "user",
        "t_start": 58.946
      },
      {
        "text": "Twenty-nine. You?",
        "t_end": 63.697,
        "speaker": "agent",
        "t_start": 62.598
      },
      {
        "text": "So what do you do for fun besides drawing?",
        "t_end": 69.206,
        "speaker": "user",
        "t_start": 66.15
      },
      {
        "text": "I read, and I walk around the city.",
        "t_end": 72.412,
        "speaker": "agent",
        "t_start": 69.726
      },
      {
        "text": "And I draw badly, often.",
        "t_end": 75.796,
        "speaker": "agent",
        "t_start": 73.542
      },
      {
        "text": "So who's your favorite daughter, if you don't mind me asking?",
        "t_end": 81.577,
        "speaker": "user",
        "t_start": 78.481
      },
      {
        "text": "Murakami, lately.",
        "t_end": 83.671,
        "speaker": "agent",
        "t_start": 82.018
      },
      {
        "text": "I haven't heard of...",
        "t_end": 87.991,
        "speaker": "user",
        "t_start": 85.477
      },
      {
        "text": "You’ve heard of Haruki Murakami, probably.",
        "t_end": 92.116,
        "speaker": "agent",
        "t_start": 88.6
      },
      {
        "text": "I haven't. Could you maybe tell me some of her work?",
        "t_end": 96.734,
        "speaker": "user",
        "t_start": 93.182
      },
      {
        "text": "\"Norwegian Wood\" is one. Good place to start.",
        "t_end": 100.836,
        "speaker": "agent",
        "t_start": 97.173
      },
      {
        "text": "Do you have any recommendations for someone who is into more fiction?",
        "t_end": 107.588,
        "speaker": "user",
        "t_start": 103.101
      },
      {
        "text": "\"Kafka on the Shore\" fits that.",
        "t_end": 111.696,
        "speaker": "agent",
        "t_start": 108.035
      },
      {
        "text": "Oh, really? Who's it by?",
        "t_end": 113.575,
        "speaker": "user",
        "t_start": 111.717
      },
      {
        "text": "Haruki Murakami, same author.",
        "t_end": 117.017,
        "speaker": "agent",
        "t_start": 114.124
      },
      {
        "text": "Makes sense. I really like your outfit today.",
        "t_end": 121.002,
        "speaker": "user",
        "t_start": 117.96
      },
      {
        "text": "Rather talk about books than outfits, honestly.",
        "t_end": 124.836,
        "speaker": "agent",
        "t_start": 121.443
      },
      {
        "text": "Yeah, sorry, my bad. Okay then, what's your favorite genre?",
        "t_end": 130.169,
        "speaker": "user",
        "t_start": 125.732
      },
      {
        "text": "Literary fiction, mostly, some magical realism.",
        "t_end": 134.017,
        "speaker": "agent",
        "t_start": 130.666
      },
      {
        "text": "So like Harry Potter?",
        "t_end": 136.679,
        "speaker": "user",
        "t_start": 135.014
      },
      {
        "text": "Not quite, more grounded, less wands.",
        "t_end": 140.376,
        "speaker": "agent",
        "t_start": 137.137
      },
      {
        "text": "Yeah, really.",
        "t_end": 145.223,
        "speaker": "agent",
        "t_start": 144.877
      },
      {
        "text": "I really like Merlin as well.",
        "t_end": 149.941,
        "speaker": "user",
        "t_start": 147.845
      },
      {
        "text": "Murakami, not Merlin. Different vibe.",
        "t_end": 153.656,
        "speaker": "agent",
        "t_start": 150.486
      },
      {
        "text": "How about Percy Jackson? Maybe you're into him.",
        "t_end": 157.694,
        "speaker": "user",
        "t_start": 155.034
      },
      {
        "text": "Not really, more for younger readers.",
        "t_end": 161.359,
        "speaker": "agent",
        "t_start": 158.151
      },
      {
        "text": "I guess that makes sense.",
        "t_end": 164.332,
        "speaker": "user",
        "t_start": 162.395
      },
      {
        "text": "So what’s yours, mystery man?",
        "t_end": 167.075,
        "speaker": "agent",
        "t_start": 164.805
      },
      {
        "text": "Probably Harry Potter.",
        "t_end": 169.984,
        "speaker": "user",
        "t_start": 168.292
      },
      {
        "text": "Figured. And your actual name?",
        "t_end": 173.01,
        "speaker": "agent",
        "t_start": 170.461
      },
      {
        "text": "My name is Bobot.",
        "t_end": 175.472,
        "speaker": "user",
        "t_start": 174.059
      },
      {
        "text": "All right, Babat. Got it.",
        "t_end": 178.378,
        "speaker": "agent",
        "t_start": 176.158
      }
    ]
  },
  {
    "id": "maya-2026-08-23-ad169e",
    "source": "session ad169e46-08d4-4c6b-8bdb-6dd000e9077b",
    "personaName": "Maya",
    "sessionSeconds": 147,
    "transcript": [
      {
        "text": "Hello.",
        "t_end": 2.59,
        "speaker": "user",
        "t_start": 1.628
      },
      {
        "text": "Morning.",
        "t_end": 6.062,
        "speaker": "agent",
        "t_start": 3.037
      },
      {
        "text": "What's your name?",
        "t_end": 7.8,
        "speaker": "user",
        "t_start": 6.589
      },
      {
        "text": "Maya.",
        "t_end": 10.262,
        "speaker": "agent",
        "t_start": 8.212
      },
      {
        "text": "Hello Maya, what are you doing here?",
        "t_end": 12.906,
        "speaker": "user",
        "t_start": 10.959
      },
      {
        "text": "Having coffee, writing a little.",
        "t_end": 15.742,
        "speaker": "agent",
        "t_start": 13.341
      },
      {
        "text": "I see.",
        "t_end": 18.426,
        "speaker": "user",
        "t_start": 17.013
      },
      {
        "text": "Alright.",
        "t_end": 19.202,
        "speaker": "agent",
        "t_start": 18.731
      },
      {
        "text": "Your coffee looks delicious.",
        "t_end": 21.268,
        "speaker": "user",
        "t_start": 20.585
      },
      {
        "text": "It’s decent. Not too sweet.",
        "t_end": 23.363,
        "speaker": "agent",
        "t_start": 21.078
      },
      {
        "text": "Not a fan of sweets, are you?",
        "t_end": 27.602,
        "speaker": "user",
        "t_start": 25.627
      },
      {
        "text": "Not usually, no.",
        "t_end": 30.116,
        "speaker": "agent",
        "t_start": 28.027
      },
      {
        "text": "So, what are you writing?",
        "t_end": 33.524,
        "speaker": "user",
        "t_start": 31.691
      },
      {
        "text": "Just notes, nothing big.",
        "t_end": 36.202,
        "speaker": "agent",
        "t_start": 33.925
      },
      {
        "text": "I love a woman who writes.",
        "t_end": 43.752,
        "speaker": "user",
        "t_start": 40.987
      },
      {
        "text": "Noted. Anything else?",
        "t_end": 46.708,
        "speaker": "agent",
        "t_start": 44.151
      },
      {
        "text": "I just wanted to compliment on your shoes. They look great.",
        "t_end": 51.614,
        "speaker": "user",
        "t_start": 48.187
      },
      {
        "text": "Not answering that.",
        "t_end": 53.712,
        "speaker": "agent",
        "t_start": 52.045
      },
      {
        "text": "So what do you do for fun?",
        "t_end": 59.254,
        "speaker": "user",
        "t_start": 57.494
      },
      {
        "text": "I draw, badly, and often.",
        "t_end": 62.282,
        "speaker": "agent",
        "t_start": 59.669
      },
      {
        "text": "Maybe I can see a couple of pictures.",
        "t_end": 68.263,
        "speaker": "user",
        "t_start": 64.942
      },
      {
        "text": "Not carrying any with me now.",
        "t_end": 70.488,
        "speaker": "agent",
        "t_start": 68.675
      },
      {
        "text": "So how long is our life?",
        "t_end": 76.255,
        "speaker": "user",
        "t_start": 73.979
      },
      {
        "text": "Twenty-nine.",
        "t_end": 77.841,
        "speaker": "agent",
        "t_start": 76.649
      },
      {
        "text": "Can you nine ha? When's your birthday?",
        "t_end": 81.792,
        "speaker": "user",
        "t_start": 79.76
      },
      {
        "text": "Not sharing that.",
        "t_end": 83.381,
        "speaker": "agent",
        "t_start": 82.241
      },
      {
        "text": "I'm sorry, that's my bad.",
        "t_end": 86.968,
        "speaker": "user",
        "t_start": 85.168
      },
      {
        "text": "Alright.",
        "t_end": 89.467,
        "speaker": "agent",
        "t_start": 87.387
      },
      {
        "text": "My name is Jake, by the way.",
        "t_end": 91.459,
        "speaker": "user",
        "t_start": 89.467
      },
      {
        "text": "Alright, Jake.",
        "t_end": 92.861,
        "speaker": "agent",
        "t_start": 91.868
      },
      {
        "text": "So what do you think about today?",
        "t_end": 101.226,
        "speaker": "user",
        "t_start": 99.387
      },
      {
        "text": "Feels calm, so far.",
        "t_end": 104.422,
        "speaker": "agent",
        "t_start": 101.675
      },
      {
        "text": "Maybe I'm out here disturbing your peace?",
        "t_end": 108.536,
        "speaker": "user",
        "t_start": 105.97
      },
      {
        "text": "You are, a bit.",
        "t_end": 110.741,
        "speaker": "agent",
        "t_start": 108.965
      },
      {
        "text": "I was just wondering if I could get to know you a bit better.",
        "t_end": 115.624,
        "speaker": "user",
        "t_start": 112.785
      },
      {
        "text": "You're wondering out loud now.",
        "t_end": 118.242,
        "speaker": "agent",
        "t_start": 116.102
      },
      {
        "text": "Yeah, true, you are a tough girl to talk to.",
        "t_end": 122.749,
        "speaker": "user",
        "t_start": 119.995
      },
      {
        "text": "Seems that way today.",
        "t_end": 124.84,
        "speaker": "agent",
        "t_start": 123.196
      },
      {
        "text": "Can I get your number?",
        "t_end": 129.972,
        "speaker": "user",
        "t_start": 128.508
      },
      {
        "text": "Not handing that out right now.",
        "t_end": 132.497,
        "speaker": "agent",
        "t_start": 130.397
      },
      {
        "text": "Tell me more about yourself.",
        "t_end": 138.505,
        "speaker": "user",
        "t_start": 136.667
      },
      {
        "text": "Not really feeling like it.",
        "t_end": 140.62,
        "speaker": "agent",
        "t_start": 138.934
      },
      {
        "text": "OK then, bye, sorry.",
        "t_end": 144.213,
        "speaker": "user",
        "t_start": 142.383
      },
      {
        "text": "Alright. Take care.",
        "t_end": 146.51,
        "speaker": "agent",
        "t_start": 144.772
      }
    ]
  },
  {
    "id": "priya-2026-08-23-f7859f",
    "source": "session f7859f67-2d7c-4eb8-8fb5-b7d4db0e8a7e",
    "personaName": "Priya",
    "sessionSeconds": 142,
    "transcript": [
      {
        "text": "Hello there.",
        "t_end": 4.071,
        "speaker": "user",
        "t_start": 2.916
      },
      {
        "text": "Hey. What's up?",
        "t_end": 6.694,
        "speaker": "agent",
        "t_start": 4.736
      },
      {
        "text": "Catching my breath between sets right now.",
        "t_end": 8.259,
        "speaker": "agent",
        "t_start": 8.039
      },
      {
        "text": "How are you doing?",
        "t_end": 10.115,
        "speaker": "user",
        "t_start": 8.917
      },
      {
        "text": "I’m fine, just mid-workout.",
        "t_end": 12.231,
        "speaker": "agent",
        "t_start": 10.531
      },
      {
        "text": "Just network.",
        "t_end": 13.926,
        "speaker": "user",
        "t_start": 12.23
      },
      {
        "text": "Yeah, mid-set, feeling strong.",
        "t_end": 15.079,
        "speaker": "agent",
        "t_start": 14.448
      },
      {
        "text": "Ja.",
        "t_end": 16.036,
        "speaker": "user",
        "t_start": 15.079
      },
      {
        "text": "You're keeping your back steady, looks fine.",
        "t_end": 17.597,
        "speaker": "agent",
        "t_start": 16.546
      },
      {
        "text": "You doing?",
        "t_end": 18.643,
        "speaker": "user",
        "t_start": 17.597
      },
      {
        "text": "Three more sets left, then done.",
        "t_end": 21.375,
        "speaker": "agent",
        "t_start": 19.07
      },
      {
        "text": "What are you doing today?",
        "t_end": 28.081,
        "speaker": "user",
        "t_start": 25.191
      },
      {
        "text": "Dumbbell shoulder press, focusing on strength.",
        "t_end": 31.514,
        "speaker": "agent",
        "t_start": 28.606
      },
      {
        "text": "Well, so you must be doing heavy weights with low reps, right?",
        "t_end": 37.793,
        "speaker": "user",
        "t_start": 32.513
      },
      {
        "text": "Yeah, heavy sets in the 6 to 8 range.",
        "t_end": 41.055,
        "speaker": "agent",
        "t_start": 38.234
      },
      {
        "text": "That's really good. I'm doing shoulders as well, but I'm doing a barbell shoulder press.",
        "t_end": 48.034,
        "speaker": "user",
        "t_start": 42.76
      },
      {
        "text": "Nice, barbell press is solid for strength.",
        "t_end": 52.774,
        "speaker": "agent",
        "t_start": 48.541
      },
      {
        "text": "Why did you choose dumbbell press over a barbell press?",
        "t_end": 57.036,
        "speaker": "user",
        "t_start": 53.084
      },
      {
        "text": "Better range of motion, and more stability work.",
        "t_end": 60.474,
        "speaker": "agent",
        "t_start": 57.468
      },
      {
        "text": "Yeah, I guess that's right.",
        "t_end": 63.46,
        "speaker": "user",
        "t_start": 61.635
      },
      {
        "text": "It’s worked well for my shoulders, keeps them healthy.",
        "t_end": 68.115,
        "speaker": "agent",
        "t_start": 63.891
      },
      {
        "text": "How long have you been working out?",
        "t_end": 70.656,
        "speaker": "user",
        "t_start": 68.688
      },
      {
        "text": "About three years seriously, lifting consistently.",
        "t_end": 74.935,
        "speaker": "agent",
        "t_start": 71.098
      },
      {
        "text": "Really? You got that physique from just three years?",
        "t_end": 79.173,
        "speaker": "user",
        "t_start": 75.643
      },
      {
        "text": "Three years of consistent training, plus dialed nutrition.",
        "t_end": 84.18,
        "speaker": "agent",
        "t_start": 79.665
      },
      {
        "text": "That's the hardest thing, right? Nutrition.",
        "t_end": 88.393,
        "speaker": "user",
        "t_start": 84.94
      },
      {
        "text": "Yeah, it took me a while to lock that in.",
        "t_end": 91.876,
        "speaker": "agent",
        "t_start": 88.898
      },
      {
        "text": "I'm still trying to do it properly. Do you have any suggestions?",
        "t_end": 97.527,
        "speaker": "user",
        "t_start": 93.326
      },
      {
        "text": "Track your protein daily, that helped me a lot.",
        "t_end": 101.494,
        "speaker": "agent",
        "t_start": 97.988
      },
      {
        "text": "What do you use for tracking?",
        "t_end": 105.675,
        "speaker": "user",
        "t_start": 103.289
      },
      {
        "text": "I use a simple app to log my meals.",
        "t_end": 108.673,
        "speaker": "agent",
        "t_start": 106.2
      },
      {
        "text": "What API do you use?",
        "t_end": 112.491,
        "speaker": "user",
        "t_start": 110.63
      },
      {
        "text": "I use one called MacroFactor lately, works well for me.",
        "t_end": 116.535,
        "speaker": "agent",
        "t_start": 113.023
      },
      {
        "text": "Oh, I know, the someone from YouTube also promoted it, right? Priya?",
        "t_end": 123.552,
        "speaker": "user",
        "t_start": 118.258
      },
      {
        "text": "Yeah, some fitness YouTubers use it too, exactly.",
        "t_end": 127.474,
        "speaker": "agent",
        "t_start": 124.061
      },
      {
        "text": "What else do you do when you're not working out?",
        "t_end": 132.414,
        "speaker": "user",
        "t_start": 129.353
      },
      {
        "text": "I work in insurance claims during the day.",
        "t_end": 135.341,
        "speaker": "agent",
        "t_start": 132.939
      },
      {
        "text": "Okay, maybe I can get your number?",
        "t_end": 139.555,
        "speaker": "user",
        "t_start": 136.841
      },
      {
        "text": "Sure, we can swap numbers if you want.",
        "t_end": 142.376,
        "speaker": "agent",
        "t_start": 140.008
      }
    ]
  },
  {
    "id": "nadia-2026-08-23-de1911",
    "source": "session de191162-eff5-47c7-b5cd-bf8f5fa37c78",
    "personaName": "Nadia",
    "sessionSeconds": 158,
    "transcript": [
      {
        "text": "Hej der.",
        "t_end": 2.768,
        "speaker": "user",
        "t_start": 1.671
      },
      {
        "text": "Hey.",
        "t_end": 5.373,
        "speaker": "agent",
        "t_start": 3.293
      },
      {
        "text": "What's your name?",
        "t_end": 8.184,
        "speaker": "user",
        "t_start": 6.97
      },
      {
        "text": "Nadia. You?",
        "t_end": 9.733,
        "speaker": "agent",
        "t_start": 8.685
      },
      {
        "text": "My name is Jake. Nice to meet you.",
        "t_end": 13.404,
        "speaker": "user",
        "t_start": 11.141
      },
      {
        "text": "Sure. Nice to meet you too.",
        "t_end": 16.025,
        "speaker": "agent",
        "t_start": 13.928
      },
      {
        "text": "So what are you doing here?",
        "t_end": 18.902,
        "speaker": "user",
        "t_start": 17.307
      },
      {
        "text": "Just looking for something for my sister.",
        "t_end": 21.795,
        "speaker": "agent",
        "t_start": 19.416
      },
      {
        "text": "Really? She's a big reader?",
        "t_end": 25.698,
        "speaker": "user",
        "t_start": 23.386
      },
      {
        "text": "Not really, but she likes nature books sometimes.",
        "t_end": 29.473,
        "speaker": "agent",
        "t_start": 26.228
      },
      {
        "text": "Is it her birthday or something? You are looking for a present?",
        "t_end": 33.95,
        "speaker": "user",
        "t_start": 30.932
      },
      {
        "text": "Yeah, birthday’s next week, I need a decent gift.",
        "t_end": 37.754,
        "speaker": "agent",
        "t_start": 34.492
      },
      {
        "text": "Well, maybe I can be of help.",
        "t_end": 41.578,
        "speaker": "user",
        "t_start": 39.174
      },
      {
        "text": "Appreciate it, Jake, but I'm just browsing around.",
        "t_end": 45.385,
        "speaker": "agent",
        "t_start": 42.121
      },
      {
        "text": "Can you tell me what more she's into? Maybe I can help.",
        "t_end": 50.656,
        "speaker": "user",
        "t_start": 47.07
      },
      {
        "text": "Mostly nature stuff, some travel essays, that’s about it.",
        "t_end": 55.454,
        "speaker": "agent",
        "t_start": 51.198
      },
      {
        "text": "How about poetry? Does she like poetry?",
        "t_end": 59.592,
        "speaker": "user",
        "t_start": 56.507
      },
      {
        "text": "No, poetry’s not her thing at all.",
        "t_end": 62.835,
        "speaker": "agent",
        "t_start": 60.21
      },
      {
        "text": "Okay, maybe, okay, tell me what do you like?",
        "t_end": 69.211,
        "speaker": "user",
        "t_start": 65.05
      },
      {
        "text": "Crime novels, mostly, and a lot of non-fiction.",
        "t_end": 73.054,
        "speaker": "agent",
        "t_start": 69.799
      },
      {
        "text": "Crime novels, huh?",
        "t_end": 76.026,
        "speaker": "user",
        "t_start": 74.456
      },
      {
        "text": "Yeah, Tana French is my go-to.",
        "t_end": 79.534,
        "speaker": "agent",
        "t_start": 76.638
      },
      {
        "text": "He doesn't seem like the kind of girl who likes crime novels, but I guess looks can be deceiving.",
        "t_end": 87.852,
        "speaker": "user",
        "t_start": 81.374
      },
      {
        "text": "Guess they can, Jake.",
        "t_end": 90.714,
        "speaker": "agent",
        "t_start": 88.551
      },
      {
        "text": "So how old is yours is to turning?",
        "t_end": 94.792,
        "speaker": "user",
        "t_start": 92.571
      },
      {
        "text": "She’s turning thirty-four next week.",
        "t_end": 98.514,
        "speaker": "agent",
        "t_start": 95.545
      },
      {
        "text": "Trifó, ha?",
        "t_end": 100.82,
        "speaker": "user",
        "t_start": 99.614
      },
      {
        "text": "Yeah. What about you, Jake, older or younger?",
        "t_end": 104.654,
        "speaker": "agent",
        "t_start": 101.564
      },
      {
        "text": "Actually, I am twenty-five. What about you?",
        "t_end": 108.552,
        "speaker": "user",
        "t_start": 105.99
      },
      {
        "text": "I'm twenty-eight. You'd guessed older?",
        "t_end": 111.971,
        "speaker": "agent",
        "t_start": 109.235
      },
      {
        "text": "No, actually, I thought you were younger. You look younger.",
        "t_end": 117.096,
        "speaker": "user",
        "t_start": 113.777
      },
      {
        "text": "Mm, flattery in a bookshop, bold move.",
        "t_end": 121.773,
        "speaker": "agent",
        "t_start": 118.261
      },
      {
        "text": "I mean, it's not flattery if it's the truth, right?",
        "t_end": 126.423,
        "speaker": "user",
        "t_start": 123.226
      },
      {
        "text": "Truth or not, you're laying it on thick, Jake.",
        "t_end": 129.974,
        "speaker": "agent",
        "t_start": 126.995
      },
      {
        "text": "So you like crime novels. What about fiction?",
        "t_end": 135.295,
        "speaker": "user",
        "t_start": 131.707
      },
      {
        "text": "Crime is fiction. Just not the sad-house kind.",
        "t_end": 139.314,
        "speaker": "agent",
        "t_start": 135.903
      },
      {
        "text": "Crime is not always fiction, you know. There is crime in day-to-day world.",
        "t_end": 145.525,
        "speaker": "user",
        "t_start": 140.338
      },
      {
        "text": "Sure, but I’m here for the books, not the news.",
        "t_end": 150.473,
        "speaker": "agent",
        "t_start": 146.143
      },
      {
        "text": "So, how about I get your number?",
        "t_end": 154.261,
        "speaker": "user",
        "t_start": 151.707
      },
      {
        "text": "Alright, I'll give you mine. You ready?",
        "t_end": 158.473,
        "speaker": "agent",
        "t_start": 154.996
      }
    ]
  },
  {
    "id": "nadia-2026-08-23-4e84c3",
    "source": "session 4e84c366-a9af-4a16-bce1-630bd51a41dc",
    "personaName": "Nadia",
    "sessionSeconds": 73,
    "transcript": [
      {
        "text": "Nadia. You?",
        "t_end": 8.171,
        "speaker": "agent",
        "t_start": 2.729
      },
      {
        "text": "Hello, what's your name?",
        "t_end": 6.061,
        "speaker": "user",
        "t_start": 4.488
      },
      {
        "text": "My name is Jake.",
        "t_end": 11.543,
        "speaker": "user",
        "t_start": 9.732
      },
      {
        "text": "Alright, Jake.",
        "t_end": 13.111,
        "speaker": "agent",
        "t_start": 12.067
      },
      {
        "text": "What are you doing here?",
        "t_end": 15.933,
        "speaker": "user",
        "t_start": 14.361
      },
      {
        "text": "Looking for a birthday gift.",
        "t_end": 19.191,
        "speaker": "agent",
        "t_start": 16.574
      },
      {
        "text": "For whom?",
        "t_end": 20.979,
        "speaker": "user",
        "t_start": 19.928
      },
      {
        "text": "For my sister.",
        "t_end": 23.691,
        "speaker": "agent",
        "t_start": 21.526
      },
      {
        "text": "Oh, how old is she turning?",
        "t_end": 26.753,
        "speaker": "user",
        "t_start": 24.509
      },
      {
        "text": "She’ll be twenty-six next week.",
        "t_end": 29.892,
        "speaker": "agent",
        "t_start": 27.309
      },
      {
        "text": "Do you need help picking out a book?",
        "t_end": 33.566,
        "speaker": "user",
        "t_start": 31.229
      },
      {
        "text": "I’m not really one for picking help.",
        "t_end": 37.072,
        "speaker": "agent",
        "t_start": 34.139
      },
      {
        "text": "Okay, how about you tell me what she's into?",
        "t_end": 41.43,
        "speaker": "user",
        "t_start": 37.951
      },
      {
        "text": "She’s into old travel books, mostly.",
        "t_end": 45.151,
        "speaker": "agent",
        "t_start": 42.058
      },
      {
        "text": "And what about you? What are you into?",
        "t_end": 48.528,
        "speaker": "user",
        "t_start": 46.337
      },
      {
        "text": "Crime novels and weird non-fiction, mostly.",
        "t_end": 52.491,
        "speaker": "agent",
        "t_start": 49.082
      },
      {
        "text": "I just saw a stuff like from Agatha Christie.",
        "t_end": 57.441,
        "speaker": "user",
        "t_start": 53.582
      },
      {
        "text": "More modern than that, Jake.",
        "t_end": 60.064,
        "speaker": "agent",
        "t_start": 58.043
      },
      {
        "text": "So who's your favorite author?",
        "t_end": 64.04,
        "speaker": "user",
        "t_start": 61.542
      },
      {
        "text": "Tana French, probably.",
        "t_end": 66.731,
        "speaker": "agent",
        "t_start": 64.782
      },
      {
        "text": "Yeah, I’ve read",
        "t_end": 73.014,
        "speaker": "agent",
        "t_start": 70.751
      }
    ]
  },
  {
    "id": "priya-2026-08-23-7b27ad",
    "source": "session 7b27ad5e-5ef8-4f49-920f-835a7f6ff84b",
    "personaName": "Priya",
    "sessionSeconds": 114,
    "transcript": [
      {
        "text": "Hello there.",
        "t_end": 2.734,
        "speaker": "user",
        "t_start": 1.801
      },
      {
        "text": "Hey. I'm just catching my breath.",
        "t_end": 7.089,
        "speaker": "agent",
        "t_start": 3.511
      },
      {
        "text": "What are you working on today?",
        "t_end": 10.485,
        "speaker": "user",
        "t_start": 8.387
      },
      {
        "text": "Heavy rows and overhead press sets.",
        "t_end": 13.689,
        "speaker": "agent",
        "t_start": 11.038
      },
      {
        "text": "So you're doing upper body.",
        "t_end": 16.84,
        "speaker": "user",
        "t_start": 14.798
      },
      {
        "text": "Yeah, upper body day today.",
        "t_end": 19.668,
        "speaker": "agent",
        "t_start": 17.443
      },
      {
        "text": "That's awesome. You look great. How long have you been working out?",
        "t_end": 24.358,
        "speaker": "user",
        "t_start": 20.971
      },
      {
        "text": "Three years, lifting seriously.",
        "t_end": 27.268,
        "speaker": "agent",
        "t_start": 24.922
      },
      {
        "text": "You know what they say, commitment is key. That's great that you got to do it for three years.",
        "t_end": 34.993,
        "speaker": "user",
        "t_start": 29.409
      },
      {
        "text": "Yeah, it's been worth it.",
        "t_end": 37.369,
        "speaker": "agent",
        "t_start": 35.651
      },
      {
        "text": "Definitely. So how do you track the, do the whole nutrition thing? So that's one thing I have been struggling with.",
        "t_end": 46.257,
        "speaker": "user",
        "t_start": 39.321
      },
      {
        "text": "I keep it simple: track protein, watch portions, no crazy rules.",
        "t_end": 52.069,
        "speaker": "agent",
        "t_start": 47.337
      },
      {
        "text": "So that's it?",
        "t_end": 55.12,
        "speaker": "user",
        "t_start": 53.794
      },
      {
        "text": "Yeah, that’s all I do, and it works for me.",
        "t_end": 58.349,
        "speaker": "agent",
        "t_start": 55.72
      },
      {
        "text": "I can see that it works for you, you look awesome.",
        "t_end": 63.237,
        "speaker": "user",
        "t_start": 60.333
      },
      {
        "text": "Thanks, consistency pays off over time.",
        "t_end": 67.11,
        "speaker": "agent",
        "t_start": 63.862
      },
      {
        "text": "What did you say your name was again?",
        "t_end": 70.856,
        "speaker": "user",
        "t_start": 68.682
      },
      {
        "text": "I’m Priya. What's yours?",
        "t_end": 73.924,
        "speaker": "agent",
        "t_start": 71.486
      },
      {
        "text": "My name is Jake.",
        "t_end": 76.546,
        "speaker": "user",
        "t_start": 74.973
      },
      {
        "text": "Nice to meet you, Jake.",
        "t_end": 78.868,
        "speaker": "agent",
        "t_start": 77.107
      },
      {
        "text": "You know, do you think you can give me a schedule later for a leg workout?",
        "t_end": 87.032,
        "speaker": "user",
        "t_start": 80.812
      },
      {
        "text": "I don't do schedules, but I can share some basics now.",
        "t_end": 90.702,
        "speaker": "agent",
        "t_start": 87.631
      },
      {
        "text": "Yeah, sure, just let me know, because yours look great.",
        "t_end": 95.173,
        "speaker": "user",
        "t_start": 91.751
      },
      {
        "text": "Squats, lunges, and Romanian deadlifts work for me.",
        "t_end": 99.668,
        "speaker": "agent",
        "t_start": 95.766
      },
      {
        "text": "That's it?",
        "t_end": 101.957,
        "speaker": "user",
        "t_start": 100.895
      },
      {
        "text": "Those three are solid, Jake, trust me.",
        "t_end": 105.469,
        "speaker": "agent",
        "t_start": 102.552
      },
      {
        "text": "I will definitely trust you because you look like you know what you are doing.",
        "t_end": 110.332,
        "speaker": "user",
        "t_start": 106.665
      },
      {
        "text": "Appreciate that, Jake. I've got to hit my next set now.",
        "t_end": 114.008,
        "speaker": "agent",
        "t_start": 110.956
      }
    ]
  },
  {
    "id": "priya-2026-08-23-5862f0",
    "source": "session 5862f0ee-cd4e-4b10-b33e-955bfa0d31f3",
    "personaName": "Priya",
    "sessionSeconds": 112,
    "transcript": [
      {
        "text": "Hello.",
        "t_end": 2.464,
        "speaker": "user",
        "t_start": 1.572
      },
      {
        "text": "Hey. Mid-set or between?",
        "t_end": 5.463,
        "speaker": "agent",
        "t_start": 2.931
      },
      {
        "text": "I'm sorry, I can't hear you properly.",
        "t_end": 9.439,
        "speaker": "user",
        "t_start": 7.044
      },
      {
        "text": "I said, mid-set or between sets?",
        "t_end": 12.443,
        "speaker": "agent",
        "t_start": 9.83
      },
      {
        "text": "I am bitween sex, what about you?",
        "t_end": 16.799,
        "speaker": "user",
        "t_start": 14.417
      },
      {
        "text": "Same, between sets right now.",
        "t_end": 19.442,
        "speaker": "agent",
        "t_start": 17.301
      },
      {
        "text": "So what are you working on today, legs?",
        "t_end": 25.92,
        "speaker": "user",
        "t_start": 22.397
      },
      {
        "text": "Upper body, mostly back.",
        "t_end": 28.442,
        "speaker": "agent",
        "t_start": 26.371
      },
      {
        "text": "Just back?",
        "t_end": 31.315,
        "speaker": "user",
        "t_start": 30.111
      },
      {
        "text": "And some shoulders too.",
        "t_end": 33.383,
        "speaker": "agent",
        "t_start": 31.779
      },
      {
        "text": "So how long have you been working out?",
        "t_end": 38.356,
        "speaker": "user",
        "t_start": 35.879
      },
      {
        "text": "About three years seriously.",
        "t_end": 40.894,
        "speaker": "agent",
        "t_start": 38.8
      },
      {
        "text": "You look great.",
        "t_end": 44.914,
        "speaker": "user",
        "t_start": 43.516
      },
      {
        "text": "Thanks. Just staying consistent with training.",
        "t_end": 47.579,
        "speaker": "agent",
        "t_start": 45.353
      },
      {
        "text": "Yeah, all consistent work adds up.",
        "t_end": 51.403,
        "speaker": "agent",
        "t_start": 48.758
      },
      {
        "text": "Definitely, consistency is key. One of the things I can't do properly is managing nutrition.",
        "t_end": 60.118,
        "speaker": "user",
        "t_start": 52.857
      },
      {
        "text": "It’s the hardest part for most people.",
        "t_end": 63.661,
        "speaker": "agent",
        "t_start": 60.587
      },
      {
        "text": "I know. Do you have any tips?",
        "t_end": 66.835,
        "speaker": "user",
        "t_start": 64.573
      },
      {
        "text": "Track your intake and plan meals ahead.",
        "t_end": 70.257,
        "speaker": "agent",
        "t_start": 67.3
      },
      {
        "text": "The problem is, usually my mom makes the meals, so I just have whatever she makes.",
        "t_end": 77.823,
        "speaker": "user",
        "t_start": 72.153
      },
      {
        "text": "Maybe add your own snacks or portions.",
        "t_end": 81.601,
        "speaker": "agent",
        "t_start": 78.26
      },
      {
        "text": "How about you? How do you track your calories?",
        "t_end": 86.1,
        "speaker": "user",
        "t_start": 83.393
      },
      {
        "text": "I use a simple app and weigh portions sometimes.",
        "t_end": 87.782,
        "speaker": "agent",
        "t_start": 86.554
      },
      {
        "text": "An app and a food scale daily.",
        "t_end": 91.643,
        "speaker": "agent",
        "t_start": 88.843
      },
      {
        "text": "Good scare, huh? Maybe I should invest in one.",
        "t_end": 95.944,
        "speaker": "user",
        "t_start": 92.91
      },
      {
        "text": "It’s a game changer for accuracy, definitely.",
        "t_end": 99.262,
        "speaker": "agent",
        "t_start": 96.376
      },
      {
        "text": "What's your name, by the way?",
        "t_end": 102.47,
        "speaker": "user",
        "t_start": 100.751
      },
      {
        "text": "Priya. And I’ve got to get this next set.",
        "t_end": 106.482,
        "speaker": "agent",
        "t_start": 102.916
      },
      {
        "text": "Oh, hello Bria, where are you from?",
        "t_end": 109.982,
        "speaker": "user",
        "t_start": 107.58
      },
      {
        "text": "From around here, local. Good chat though.",
        "t_end": 111.901,
        "speaker": "agent",
        "t_start": 110.624
      }
    ]
  },
  {
    "id": "nadia-2026-08-23-0a9b9c",
    "source": "session 0a9b9c89-8f10-428e-84bb-096f267b1ec7",
    "personaName": "Nadia",
    "sessionSeconds": 120,
    "transcript": [
      {
        "text": "Hello.",
        "t_end": 3.897,
        "speaker": "user",
        "t_start": 2.91
      },
      {
        "text": "Hey.",
        "t_end": 6.61,
        "speaker": "agent",
        "t_start": 4.351
      },
      {
        "text": "What's your name?",
        "t_end": 9.772,
        "speaker": "user",
        "t_start": 8.508
      },
      {
        "text": "Nadia.",
        "t_end": 11.05,
        "speaker": "agent",
        "t_start": 10.159
      },
      {
        "text": "Yeah.",
        "t_end": 11.948,
        "speaker": "user",
        "t_start": 11.049
      },
      {
        "text": "Yeah, that’s it.",
        "t_end": 13.109,
        "speaker": "agent",
        "t_start": 12.41
      },
      {
        "text": "Hello.",
        "t_end": 14.157,
        "speaker": "user",
        "t_start": 13.109
      },
      {
        "text": "Nadia. You?",
        "t_end": 15.433,
        "speaker": "agent",
        "t_start": 14.551
      },
      {
        "text": "Claudia.",
        "t_end": 16.481,
        "speaker": "user",
        "t_start": 15.433
      },
      {
        "text": "Yeah, that's it.",
        "t_end": 17.826,
        "speaker": "agent",
        "t_start": 16.889
      },
      {
        "text": "Tak, a teď.",
        "t_end": 19.116,
        "speaker": "user",
        "t_start": 17.826
      },
      {
        "text": "Nadia.",
        "t_end": 20.814,
        "speaker": "agent",
        "t_start": 19.53
      },
      {
        "text": "Hello Nadia, what are you doing here?",
        "t_end": 25.396,
        "speaker": "user",
        "t_start": 23.167
      },
      {
        "text": "Looking for a gift, not much luck.",
        "t_end": 28.33,
        "speaker": "agent",
        "t_start": 25.839
      },
      {
        "text": "Oh really? Maybe I can help.",
        "t_end": 32.29,
        "speaker": "user",
        "t_start": 29.997
      },
      {
        "text": "That's nice of you, but I'm just browsing.",
        "t_end": 35.711,
        "speaker": "agent",
        "t_start": 32.684
      },
      {
        "text": "What are you looking again for?",
        "t_end": 39.44,
        "speaker": "user",
        "t_start": 36.715
      },
      {
        "text": "My sister, her birthday's coming up.",
        "t_end": 42.789,
        "speaker": "agent",
        "t_start": 40.022
      },
      {
        "text": "Oh really? How old is she, Danny?",
        "t_end": 46.486,
        "speaker": "user",
        "t_start": 43.942
      },
      {
        "text": "She's turning thirty-two next week.",
        "t_end": 49.51,
        "speaker": "agent",
        "t_start": 46.961
      },
      {
        "text": "Oh really? Damn. Okay, what is it into, maybe I can help.",
        "t_end": 55.283,
        "speaker": "user",
        "t_start": 51.606
      },
      {
        "text": "She likes history, bit of travel stuff.",
        "t_end": 58.751,
        "speaker": "agent",
        "t_start": 55.77
      },
      {
        "text": "Travel stuff, huh? So is she that much into traveling?",
        "t_end": 64.332,
        "speaker": "user",
        "t_start": 60.008
      },
      {
        "text": "More reading about it than actually going.",
        "t_end": 67.469,
        "speaker": "agent",
        "t_start": 64.777
      },
      {
        "text": "What about you? What are you into?",
        "t_end": 70.668,
        "speaker": "user",
        "t_start": 68.682
      },
      {
        "text": "Crime novels, non-fiction mostly.",
        "t_end": 74.569,
        "speaker": "agent",
        "t_start": 71.082
      },
      {
        "text": "Oh, so if I could guess, maybe Tanya Frey?",
        "t_end": 78.875,
        "speaker": "user",
        "t_start": 75.202
      },
      {
        "text": "Yeah, rereading one right now, actually.",
        "t_end": 81.85,
        "speaker": "agent",
        "t_start": 79.301
      },
      {
        "text": "What's your favorite book from her?",
        "t_end": 85.865,
        "speaker": "user",
        "t_start": 83.368
      },
      {
        "text": "Probably The Likeness, read it twice.",
        "t_end": 88.928,
        "speaker": "agent",
        "t_start": 86.288
      },
      {
        "text": "Yeah, it's that good, or I'm",
        "t_end": 92.498,
        "speaker": "agent",
        "t_start": 92.179
      },
      {
        "text": "Who's your favorite character there?",
        "t_end": 94.75,
        "speaker": "user",
        "t_start": 94.372
      },
      {
        "text": "It's Cassie for me. You?",
        "t_end": 96.371,
        "speaker": "agent",
        "t_start": 94.896
      },
      {
        "text": "cashy",
        "t_end": 99.615,
        "speaker": "user",
        "t_start": 98.452
      },
      {
        "text": "Yeah, she’s sharp. You got a favorite?",
        "t_end": 102.649,
        "speaker": "agent",
        "t_start": 100.038
      },
      {
        "text": "I'm more into fiction, you know, Harry Potter and stuff.",
        "t_end": 108.011,
        "speaker": "user",
        "t_start": 104.071
      },
      {
        "text": "Bit lighter than my usual reads, but fair enough.",
        "t_end": 111.77,
        "speaker": "agent",
        "t_start": 108.528
      },
      {
        "text": "Anyway, so what are you doing later tonight?",
        "t_end": 116.917,
        "speaker": "user",
        "t_start": 113.864
      },
      {
        "text": "Meeting my sister soon, probably off in a minute.",
        "t_end": 120.063,
        "speaker": "agent",
        "t_start": 117.35
      }
    ]
  }
]
