'use client'

/**
 * The hero: a rep, on the screen a rep actually runs on.
 *
 * §11 asks for "a live 30-second demo rep with no sign-up. The product sells
 * itself or it doesn't sell." A genuinely live rep cannot go here — it needs a
 * microphone, a WebRTC session and an unauthenticated route that spends money
 * on a stranger, which is what `maySpend` exists to prevent. So this is a rep
 * played back, on the real clock.
 *
 * ── WHY THIS IS NOT A TRANSCRIPT THREAD ─────────────────────────────────
 *
 * It was, and that was the wrong call: a scrolling column of chat bubbles is
 * the visual language of texting, so the first thing a stranger understood
 * about a voice product was that it was a messaging app. The mistake was not
 * styling — it was that the live rep screen in this product HAS no thread.
 * `/rep/[persona]/live` is the orb, a timer, and one caption at a time. This
 * matches it, which fixes the impression and is more honest about what
 * arrives.
 *
 * ── THE AUDIO ───────────────────────────────────────────────────────────
 *
 * `npm run hero:audio` records both sides into `public/hero/manifest.json`
 * plus one clip per turn. When that file is present this plays them and both
 * meters are driven by a real AnalyserNode over the audio — §02 rule 3,
 * satisfied rather than dodged. Until it is run, the fallback below plays
 * silently and the frame says so.
 *
 * The two sides are not equivalent and the stamp says so. His lines are
 * authored and read aloud by a speech model; hers are generated by the real
 * persona and are whatever she said. Advertising hand-written character lines
 * as the product is the thing to avoid, so the provenance of each half is
 * printed rather than implied.
 */

import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react'
import Link from 'next/link'
import { Mic, Play, RotateCcw, Volume2 } from 'lucide-react'

/** Three minutes, the same number `rep-rules.ts` calls `DATING_DURATION_MS`. */
const REP_SECONDS = 180

interface Turn {
  who: 'you' | 'her'
  text: string
  /** How long this turn holds the screen. */
  ms: number
  /** Her clip, relative to `public/`. Absent without a capture. */
  audio?: string
}

/** How one side of the rep was produced. Printed, not decorative — see the stamp. */
interface Voiceprint {
  voice?: string
  model?: string
  /** True for his half, which reads an authored script. False for hers. */
  scripted?: boolean
}

interface Manifest {
  persona: string
  her?: Voiceprint
  his?: Voiceprint
  totalMs: number
  turns: Turn[]
}

/**
 * The fallback rep. Nadia, tier 1, bookshop.
 *
 * His five lines are the authored demo script and are the same ones
 * `scripts/hero-audio.ts` sends. Hers are a stand-in for the shape until the
 * capture has been run — plausible, deliberately unremarkable, and replaced
 * wholesale by the manifest.
 */
const FALLBACK: Turn[] = [
  { who: 'you', text: "That's the third one you've picked up and put back.", ms: 2600 },
  { who: 'her', text: 'I know. None of them are right.', ms: 2200 },
  { who: 'you', text: 'What does she actually read? Not what you think she should read.', ms: 3400 },
  { who: 'her', text: 'Crime, mostly. The airport kind. She would not admit that.', ms: 3800 },
  { who: 'you', text: "Then don't buy her literature. Buy her the thing she'd be embarrassed to be seen with.", ms: 4200 },
  { who: 'her', text: 'Hm. That is annoyingly good advice.', ms: 2600 },
  { who: 'you', text: "I've got a shelf of those. I keep them behind the good ones.", ms: 3200 },
  { who: 'her', text: 'Everyone does. Nobody says it out loud.', ms: 2800 },
  { who: 'you', text: "Anyway — good luck with the sister. I'll let you get on.", ms: 3200 },
  { who: 'her', text: 'Thanks. Genuinely.', ms: 1800 },
]

/**
 * Warmth after each turn, as the meter reads it.
 *
 * Level 1 is authored to be nearly impossible to fail, so it climbs. Note that
 * it crosses 65 and nothing on the screen acknowledges it: arming is silent
 * (§05), and a demo that announced it would be teaching the wrong thing about
 * the product on the one screen where somebody is deciding.
 */
const WARMTH = [16, 22, 31, 40, 52, 58, 63, 67, 71, 70]

/** Nadia's authored ramp, from `lib/personas/visual.ts`. Not an accent (D9). */
const NADIA = { deep: '#473337', core: '#a8384f', sheen: '#d7c1c5' } as const

function clock(secondsLeft: number): string {
  const whole = Math.max(0, Math.ceil(secondsLeft))
  return `${Math.floor(whole / 60)}:${String(whole % 60).padStart(2, '0')}`
}

/** The five bands the UI shows, on the engine's own thresholds. */
function bandVar(warmth: number): string {
  if (warmth >= 80) return 'var(--band-invested)'
  if (warmth >= 60) return 'var(--band-engaged)'
  if (warmth >= 40) return 'var(--band-open)'
  if (warmth >= 20) return 'var(--band-guarded)'
  return 'var(--band-closed)'
}

function bandName(warmth: number): string {
  if (warmth >= 80) return 'Invested'
  if (warmth >= 60) return 'Engaged'
  if (warmth >= 40) return 'Open'
  if (warmth >= 20) return 'Guarded'
  return 'Closed'
}

type Phase = 'idle' | 'playing' | 'done'

const BLOCKS = 14

/**
 * One side's level meter.
 *
 * `measured` is the honest switch: with a clip behind it the blocks follow real
 * amplitude, and without one they light flat, which claims only that this side
 * has the turn.
 */
function Blocks({ live, measured, filled }: { live: boolean; measured: boolean; filled: number }) {
  return (
    <div className={`stage__blocks${measured ? '' : ' stage__blocks--flat'}`}>
      {Array.from({ length: BLOCKS }, (_, block) => (
        <span key={block} className={live && (!measured || block < filled) ? 'on' : undefined} />
      ))}
    </div>
  )
}

export function RepReplay() {
  const [turns, setTurns] = useState<Turn[]>(FALLBACK)
  const [hasAudio, setHasAudio] = useState(false)
  const [probed, setProbed] = useState(false)
  const [her, setHer] = useState<Voiceprint | null>(null)
  const [his, setHis] = useState<Voiceprint | null>(null)
  const [phase, setPhase] = useState<Phase>('idle')
  const [index, setIndex] = useState(-1)
  const [elapsed, setElapsed] = useState(0)
  const [level, setLevel] = useState(0)

  const root = useRef<HTMLDivElement | null>(null)
  const audioEl = useRef<HTMLAudioElement | null>(null)
  const analyser = useRef<AnalyserNode | null>(null)
  const timer = useRef<number | null>(null)
  const frame = useRef<number | null>(null)
  const startedAt = useRef(0)

  // The capture may not have been run. Absent manifest is the normal case in
  // development and must never look like an error.
  useEffect(() => {
    let live = true
    fetch('/hero/manifest.json')
      .then((response) => (response.ok ? response.json() : null))
      .then((manifest: Manifest | null) => {
        if (!live || !manifest?.turns?.length) return
        setTurns(manifest.turns)
        setHasAudio(manifest.turns.some((turn) => !!turn.audio))
        // Stamped from the manifest, never hardcoded: the take is captured on
        // whatever OPENAI_REALTIME_MODEL was set to, and a model name printed
        // on a public page has to be the one that actually spoke.
        setHer(manifest.her ?? null)
        setHis(manifest.his ?? null)
      })
      .catch(() => undefined)
      // Settled, either way. Nothing may auto-start before this: see below.
      .finally(() => { if (live) setProbed(true) })
    return () => { live = false }
  }, [])

  const stop = useCallback(() => {
    if (timer.current !== null) { window.clearTimeout(timer.current); timer.current = null }
    if (frame.current !== null) { cancelAnimationFrame(frame.current); frame.current = null }
    const element = audioEl.current
    if (element) { element.pause(); element.currentTime = 0 }
  }, [])

  /**
   * The meter.
   *
   * With a clip loaded this is real amplitude off a real AnalyserNode. Without
   * one it is a steady fill that means "she has the turn" — a turn indicator
   * rather than a waveform, because a realistic-looking trace with no sound
   * behind it is exactly the canned visualiser §02 rule 3 forbids.
   */
  const meter = useCallback(() => {
    const node = analyser.current
    if (!node) return
    const data = new Uint8Array(node.frequencyBinCount)
    const tick = () => {
      node.getByteTimeDomainData(data)
      let peak = 0
      for (const sample of data) peak = Math.max(peak, Math.abs(sample - 128) / 128)
      setLevel(Math.min(1, peak * 2.4))
      frame.current = requestAnimationFrame(tick)
    }
    frame.current = requestAnimationFrame(tick)
  }, [])

  const advance = useCallback((next: number, list: Turn[], sound: boolean) => {
    if (next >= list.length) {
      setPhase('done')
      setLevel(0)
      return
    }
    setIndex(next)
    const turn = list[next]!
    setLevel(turn.who === 'her' && !sound ? 0.55 : 0)

    if (sound && turn.audio && audioEl.current) {
      const element = audioEl.current
      element.src = turn.audio
      void element.play().catch(() => undefined)
    }

    timer.current = window.setTimeout(() => advance(next + 1, list, sound), turn.ms)
  }, [])

  const play = useCallback((sound: boolean) => {
    stop()
    setElapsed(0)
    setPhase('playing')
    startedAt.current = performance.now()

    if (sound && audioEl.current && !analyser.current) {
      try {
        const Ctx = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
        if (Ctx) {
          const ctx = new Ctx()
          const source = ctx.createMediaElementSource(audioEl.current)
          const node = ctx.createAnalyser()
          node.fftSize = 512
          source.connect(node)
          node.connect(ctx.destination)
          analyser.current = node
          meter()
        }
      } catch {
        // No analyser is a quieter meter, never a broken hero.
      }
    }

    advance(0, turns, sound)
  }, [advance, meter, stop, turns])

  // The clock. Counts down from three minutes because that is what the real
  // one does — this is the opening of a rep, not a format of its own.
  useEffect(() => {
    if (phase !== 'playing') return
    const id = window.setInterval(() => {
      setElapsed((performance.now() - startedAt.current) / 1000)
    }, 200)
    return () => window.clearInterval(id)
  }, [phase])

  // Reduced motion gets the finished frame, at rest, with nothing moving —
  // and it has to be a COHERENT frame: the clock where the excerpt ends and
  // the meter where the rep left it, not a closing card over a cold 3:00.
  useEffect(() => {
    if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    setPhase('done')
    setIndex(turns.length - 1)
    setElapsed(turns.reduce((sum, turn) => sum + turn.ms, 0) / 1000)
  }, [turns])

  // Without audio there is no gesture to wait for, so it starts itself once it
  // is on screen. With audio it must not: a page that makes noise on its own
  // is a page people close.
  //
  // `probed` is load-bearing and this effect is wrong without it. The manifest
  // arrives over the network, so on the first pass `hasAudio` is false whether
  // or not there is a capture — and this effect runs long before the fetch
  // settles. Left ungated it wins the race on every desktop load, starts the
  // MUTED fallback, and by the time the audio is known about the phase is no
  // longer `idle`, so "Hear a rep" never renders. The result is a hero that
  // plays a whole silent rep with no way to hear it, and a stamp that says
  // `Recorded` while it does. Wait for the answer before assuming there is none.
  useEffect(() => {
    if (!probed || hasAudio || phase !== 'idle') return
    const node = root.current
    if (!node) return
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    const rect = node.getBoundingClientRect()
    if (rect.top < window.innerHeight && rect.bottom > 0) { play(false); return }
    if (typeof IntersectionObserver === 'undefined') return
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) { observer.disconnect(); play(false) }
      }
    }, { threshold: 0.35 })
    observer.observe(node)
    return () => observer.disconnect()
  }, [probed, hasAudio, phase, play])

  useEffect(() => stop, [stop])

  const totalMs = turns.reduce((sum, turn) => sum + turn.ms, 0)
  const current = index >= 0 ? turns[index] : undefined
  // The meter holds its final reading on the closing card. A rep that ends and
  // drops the number to zero would be saying something that did not happen.
  const warmth = index >= 0 ? (WARMTH[Math.min(index, WARMTH.length - 1)] ?? 0) : 0
  const done = phase === 'done'
  const speaking = current?.who === 'her' && phase === 'playing'
  const listening = current?.who === 'you' && phase === 'playing'
  const filled = Math.round(level * BLOCKS)

  return (
    <div className="replay" ref={root}>
      <div className={`stage${speaking ? ' stage--speaking' : ''}`}>
        <div className="stage__top">
          <span className="label">Tier 1 · Second-hand bookshop</span>
          <span className="stage__clock data">{clock(REP_SECONDS - elapsed)}</span>
        </div>

        <div className="stage__body">
          <div
            className="stage__orb"
            style={{
              '--orb-deep': NADIA.deep,
              '--orb-core': NADIA.core,
              '--orb-sheen': NADIA.sheen,
              '--orb-chroma': Math.min(100, Math.max(0, warmth)) / 100,
              '--orb-level': speaking ? level : 0,
            } as CSSProperties}
            aria-hidden="true"
          />

          <div className="stage__caption" aria-live="polite">
            {done ? (
              <>
                {/* The number is measured, not written: the fallback runs about
                    thirty seconds and a captured take runs longer, and a caption
                    that names the wrong one is a small lie on the first screen. */}
                <strong>That was {Math.round(totalMs / 1000)} seconds</strong>
                <p>Yours is three minutes, and she does not have a script either.</p>
              </>
            ) : current ? (
              <>
                <strong>{current.who === 'you' ? 'You' : 'Nadia'}</strong>
                <p>{current.text}</p>
              </>
            ) : (
              <>
                <strong>Nadia</strong>
                <p className="mute">She is looking for a birthday present for her sister and getting nowhere.</p>
              </>
            )}
          </div>

          {/* Both sides are measured now that both sides have a clip. Without
              audio every block lights at a flat height instead — that reads as
              "this one has the turn", which is true, rather than as a level
              nobody sampled. */}
          <div className="stage__meters">
            <div className={`stage__meter${listening ? ' stage__meter--live' : ''}`} aria-hidden="true">
              <span className="label"><Mic size={11} strokeWidth={2} aria-hidden="true" /> You</span>
              <Blocks live={listening} measured={hasAudio} filled={filled} />
            </div>
            <div className={`stage__meter${speaking ? ' stage__meter--live' : ''}`} aria-hidden="true">
              <span className="label">Nadia</span>
              <Blocks live={speaking} measured={hasAudio} filled={filled} />
            </div>
          </div>
        </div>

        <div className="stage__warmth">
          <span className="label">Warmth</span>
          <strong className="data" style={{ color: bandVar(warmth) }}>{warmth}</strong>
          <span className="stage__band">{bandName(warmth)}</span>
          <div className="stage__track"><i style={{ width: `${warmth}%`, background: bandVar(warmth) }} /></div>
        </div>

        {phase === 'idle' && hasAudio ? (
          <button type="button" className="stage__invite" onClick={() => play(true)}>
            <span className="arena-button arena-button--primary"><Volume2 size={16} strokeWidth={1.75} /> Hear a rep</span>
            <span className="label">{Math.round(totalMs / 1000)} seconds · sound on</span>
          </button>
        ) : null}
      </div>

      <audio ref={audioEl} preload="none" />

      <div className="replay__controls">
        <span className="replay__stamp label">
          {hasAudio
            ? `Recorded · her ${her?.model ?? 'realtime'}, unscripted · his ${his?.model ?? 'tts'}, read`
            : 'Replay · muted preview · demo script'}
        </span>
        <div className="replay__buttons">
          {done ? (
            <button type="button" className="arena-button arena-button--secondary arena-button--sm" onClick={() => play(hasAudio)}>
              <RotateCcw size={14} strokeWidth={1.75} /> Again
            </button>
          ) : phase === 'idle' && !hasAudio ? (
            <button type="button" className="arena-button arena-button--secondary arena-button--sm" onClick={() => play(false)}>
              <Play size={14} strokeWidth={1.75} /> Play
            </button>
          ) : (
            <Link href="/signup" className="arena-button arena-button--secondary arena-button--sm">Run your own</Link>
          )}
        </div>
      </div>
    </div>
  )
}
